[project]
name = "call-me-maybe"
version = "1.0.0"
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "pydantic>=2",
    "accelerate",
    "llm-sdk",
]

[tool.uv.sources]
llm-sdk = { path = "llm_sdk" }

[dependency-groups]
dev = [
    "mypy",
    "flake8",
    "pytest",
]

[tool.uv]
package = false

[tool.mypy]
python_version = "3.12"
exclude = ["llm_sdk", ".venv"]

[[tool.mypy.overrides]]
module = "llm_sdk"
follow_imports = "skip"

[[tool.mypy.overrides]]
module = ["test_io", "test_pipeline", "test_grammars", "test_vocab"]
ignore_missing_imports = true
